### ISSUE TITLE
HDMI Input not showing up after latest update

### ISSUE THREAD

**Issue by TheEngineerGuy** [mmende/homebridge-samsungtv-control2#8] opened 2020-07-22 03:12 UTC
@mmende After the update this morning, HDMI input has stopped appearing. Any way to fix it? I tried add it as a custom input, but it still doesn't show up.

Anyway around it?

**Comment by mmende** [comment] 2020-07-22 05:33
Have you tried removing it from the home app and adding it back again?

I removed every preinstalled input source but tv so that no apps show up that won't work anyway on some models. Furthermore as there are KEY_HDMI and KEY_HDMI1-KEY_HDMI4 as possible keys available for hdmi and I don't know which of these work for what model I let the users add hdmi themselves. I added it myself back successfully like this:

```json
{
  "name": "HDMI",
  "keys": "hdmi"
}
```

**Comment by TheEngineerGuy** [comment] 2020-07-22 13:59
I tried a few different ways, including clearing cached accessory, removing accessory from home app, restarting homebridge and then re-adding the accessory, but I only get TV input now.

Instead of relying on auto population of HDMI, I added the code that you advised above, and then cleared cached accessory, removed accessory from home app and then restarted the HB again, re-added the accessory but no luck.

**Comment by TheEngineerGuy** [comment] 2020-07-22 14:07
Just an FYI, the previous version would show me 3 inputs by default: TV, HDMI and Youtube. Now I only see TV, no matter what I do.

**Comment by mmende** [comment] 2020-07-22 14:07
Hm ok strange... You could also (after removing the tv from home) click on the tree dots in the upper right corner of homebridge ui -> `Homebridge Settings` -> under Reset `Unpair Bridges / Cameras / TVs / External Accessories` (button on the right) -> and then click on the trash icon next to your tv -> restart homebridge and then add the tv in home again
... this helped me when I was not able to discover the tv anymore even after deleting caches etc.

**Comment by TheEngineerGuy** [comment] 2020-07-22 14:08
yep, that is how I removed the cached accessory.

**Comment by TheEngineerGuy** [comment] 2020-07-22 14:09
I agree, quite strange indeed. 

I can try resetting my homebridge cache as a whole, and try again if you think that may help.

**Comment by mmende** [comment] 2020-07-22 14:10
Maybe... the homebridge cache is a mystery sometimes

**Comment by TheEngineerGuy** [comment] 2020-07-22 15:37
So I tried two different approaches, with same result. All I see is TV input.

1. Without Input config:
a. Hard reset Persist and Accessory cache
b. Remove all HB accessories and HB hub from Home App
c. Remove HDMI input config from HB config
d. Restart HB
e. Add All accessories to Home App

2. With HDMI Input config:
a. Hard reset Persist and Accessory cache
b. Remove all HB accessories and HB hub from Home App
c. Add HDMI input config to HB config
d. Restart HB
e. Add All accessories to Home app

**Comment by TheEngineerGuy** [comment] 2020-07-22 15:41
My config right now is as below:

```
        {
            "devices": [
                {
                    "name": "Bonus Room TV",
                    "usn": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "remoteControlPort": 36115,
                    "inputs": [
                        {
                            "name": "HDMI",
                            "keys": "hdmi"
                        }
                    ]
                }
            ],
            "platform": "SamsungTVControl"
        }
```

**Comment by mmende** [comment] 2020-07-22 16:30
Hm ok... it sounds like the device settings from your config are not applied to the discovered device config for some reason.
There is also a file that stores discovered devices so that when homebridge restarts e.g., the plugin still knows which devices it discovered last time so that even turned off tv's can be added. To remove this file you could open the terminal in homebridge ui and check with `ls -lha` if the directory `.node-persist` exists and just delete it with `rm -rf .node-persist`. But I wouldn't expect the internal config to affect the inputs unfortunately. This is just the last idea I have for now.

**Comment by TheEngineerGuy** [comment] 2020-07-22 16:37
I ran the following just now. Still the same.

```
sudo hb-service stop
ls /var/lib/homebridge/
sudo rm -dR /var/lib/homebridge/accessories
sudo rm -dR /var/lib/homebridge/persist
sudo rm -dR /var/lib/homebridge/.node-persist
ls /var/lib/homebridge/
sudo hb-service start
```

**Comment by TheEngineerGuy** [comment] 2020-07-22 16:42
Funny thing is, your previous version was working just fine. It was showing me 3 inputs, and switch was working fine between them. TV, HDMI and YouTube.

**Comment by mmende** [comment] 2020-07-22 17:19
The strange thing is that I didn't change that much about the inputs logic. I basically just removed HDMI and YoutTube as preset inputs and added apps as possible keys.
When you start homebridge in debug mode, does a message like `[SamsungTVControl] Found overwrites for "your tv's name"` appear in the logs?

**Comment by TheEngineerGuy** [comment] 2020-07-22 17:28
You know what, I think that is it. Possibly the config to add additional inputs was never working, and when you removed the preset, it took the inputs that I had with it.

**Comment by mmende** [comment] 2020-07-22 17:57
Did you remove uuid: from the usn in your config maybe? I just saw that it is not particularly precise in the readme that you have to use the whole usn value (with uuid:...)

**Comment by TheEngineerGuy** [comment] 2020-07-22 17:59
It is still there, I just abstracted it with"xxxxxxxxx" before pasting it here in public view.

**Comment by mmende** [comment] 2020-07-22 18:05
ok, i'm running out of ideas for now

**Comment by TheEngineerGuy** [comment] 2020-07-22 18:08
Yea, I wonder if it is linked to another issue someone had posted that their custom inputs are not working at all.

**Comment by mmende** [comment] 2020-07-22 18:12
Did you try removing the accessory file by hand or only via homebridge ui?

**Comment by mmende** [comment] 2020-07-22 19:12
I just published a new version with minor adjustments to inputs as well. Among other things I've added the CurrentVisibilityState characteristic to the input sources which as far as I understood can show or hide input sources. However I wouldn't expect to much since the fact that your logs didn't mention anything like `Found overwrites` looks more like the plugin doesn't get the config or the device config correctly.

**Comment by TheEngineerGuy** [comment] 2020-07-22 19:14
Yea, I think your hunch is right. For some odd reason plugin is not getting the config. But let me give it a shot and see.

**Comment by TheEngineerGuy** [comment] 2020-07-22 19:42
'-' input is strange. 

When I choose 'TV' input from plugin, it switches television to 'TV' input, but then plugin goes back to displaying '-', even though the input on television is still 'TV'.

**Comment by mmende** [comment] 2020-07-22 19:48
I didn't find a better label for it but that behaviour is what it's supposed to do. The problem is that if you e.g. switched to a channel by using homekit and then switched away to another channel with the real remote you could not switch back to that channel via homekit because it would still think it is on that channel already because there is no way of knowing on which channel the tv currently is. Therefore I introduced '-' as pseudo input and always switch back to this input after 3s.

**Comment by TheEngineerGuy** [comment] 2020-07-22 19:52
Ok that makes sense. now the trouble left is why isn't the plugin picking up the json

**Comment by mmende** [comment] 2020-07-22 19:55
I'll continue investigating tomorrow. Maybe I can add a debug message only logging the config the plugin got from homebridge...

**Comment by TheEngineerGuy** [comment] 2020-07-22 19:55
that would help.

**Comment by TheEngineerGuy** [comment] 2020-07-22 20:22
Ok I found another "proof" of config not being picked up. No matter what 'name' I set in the config, it does not change the name of the device. So, I think we can assume at this point that config is definitely not being picked up.

**Comment by mmende** [comment] 2020-07-23 06:08
I just published v2.0.0-alpha.9 which logs the config it receives at startup when started in debug mode.

**Comment by TheEngineerGuy** [comment] 2020-07-23 14:02
`[SamsungTVControl] Found config for unknown device`

Looks like it picked up the config. But somehow it doe snot recognise the device configured in there. I wonder if I have to add 'uuid:' in usn line to make it recognise the device.

**Comment by TheEngineerGuy** [comment] 2020-07-23 14:04
I think that was it! I missed adding 'uuid:' in usn definition box. 

`[SamsungTVControl] Found config for device "[TV]BonusRoom" (UN60ES6100)`

**Comment by mmende** [comment] 2020-07-23 14:05
Yes it's required... usn must be the full string including 'uuid:' otherwise the plugin won't find the device

**Comment by TheEngineerGuy** [comment] 2020-07-23 14:07
Yep, I missed it. 

For the cloud system that I architected for my employer, we create JSONs with GUIDs, but never enter the term GUID in there, so I just used the same method. Which obviously was in correct here.

**Comment by mmende** [comment] 2020-07-23 14:08
Awesome... tell me when the inputs work as expected so I can close the issue. I might add some extra notes in the readme to clarify that usn includes `uuid:`

**Comment by TheEngineerGuy** [comment] 2020-07-23 14:14
Ok, I see HDMI in there now. 

But if I name it anything other than HDMI, like HDMI3 even, it doesn't show up. Is there a limited set of keywords that I can use to name it?

**Comment by mmende** [comment] 2020-07-23 14:17
There should be no limitations regarding the input names except they have to be distinct. Remember that you always have to remove the tv from home, restart homebridge and add it again for changed inputs to be visible in home.

**Comment by TheEngineerGuy** [comment] 2020-07-23 14:18
Gotcha. Let me try that. 

On a side note, HDMI input showed up with me removing and re-adding TV. So that is what confused me.

**Comment by TheEngineerGuy** [comment] 2020-07-23 14:22
Can confirm, removing and re-adding shows the new names.

Thanks again Martin. I guess if I would have read your config details a bit more closely, I wouldn't be here, but thanks for pulling me out.

Atleast we got a good debug mode check out of, which tells us if config is being applied for the device found or not, which is what triggered me to check my config.

**Closed** 2020-07-23 14:23 UTC

**Comment by mmende** [comment] 2020-07-23 14:25
No problem. At least issues like these help improve the documentation 😉

**Comment by jonasman** [comment] 2022-04-07 08:47
Interesting that i tried most of the things listed here and still cannot add any input. I See "-" and "TV" only, however i tried to add multiple inputs in the json config
