### ISSUE TITLE
Input Discovery - Anynet/CEC Devices

### ISSUE THREAD

**Issue by TheEngineerGuy** [mmende/homebridge-samsungtv-control2#2] opened 2020-07-17 19:23 UTC
It was able to successfully discover TV and all HDMI inputs. 

But since there is no AnyNet or CEC counterpart for HDMI inputs available via this plugin, when input is changed to an HDMI device, it does not go to its Anynet/CEC counterpart, which removes the ability of controlling the HDMI device via TV remote once we switch to it.

Can Anynet/CEC inputs be discovered and added to the Input selection menu?

**Comment by TheEngineerGuy** [comment] 2020-07-17 20:12
So, I found a trick. If after Selecting HDMI from app, I refresh the Sources by pressing 'Source' and then 'Red' keys, it auto switches to Anynet/CEC.

I wonder if there is a way through API to call for 'Source refresh'.

**Comment by mmende** [comment] 2020-07-22 05:46
Do you mean the problem is, that the input source stays on the last selected input source in home? I thought about switching back the input to tv after a short period of time. Could that solve your problem?

**Comment by TheEngineerGuy** [comment] 2020-07-22 13:49
Well what happens is, if a device is CEC/AnyNet compatible, along with the normal HDMI Source, it shows an AnyNet Source in the list. So, to get the AnyNet/CEC functionality of controlling that source via TV remote, there are two ways:
1. Select AnyNet Source directly
2. Select the HDMI Source and then refresh the Source list

What currently happens via input selection from the plugin, it stays on HDMI input that you select and does not go over to its respective AnyNet source, which makes the TV remote not control the CEC/AnyNet device. 

So, what I am suggesting is:
1. Either we allow to populate and select AnyNet sources directly, or
2. After selecting HDMI source, we call for a source refresh.

Either of those ways would allow TV remote to control the AnyNet/CEC device after we switch over to that input.

**Comment by mmende** [comment] 2020-07-22 13:54
Ah ok. Have you tried sending `KEY_ANYNET` instead of `KEY_HDMI`?

**Comment by TheEngineerGuy** [comment] 2020-07-22 13:56
Hmm.. That is worth a shot, I can try that. However, since last update I am unable to set additional inputs. The only Input that shows up now is TV. I added a separate thread for that.

**Comment by mmende** [comment] 2020-07-22 13:57
Also there are these keys related to anynet: `KEY_AUTO_ARC_ANYNET_AUTO_START` and `KEY_AUTO_ARC_ANYNET_MODE_OK`

**Comment by mmende** [comment] 2020-07-22 13:58
Yeah I saw that issue. Have you tried remove the tv from the home app, restart homebridge after you made your adjustments and then add it back to home again?

**Comment by TheEngineerGuy** [comment] 2020-07-22 14:01
Yep, just responded to that thread as well. I saw the list of key for apps, is there a list of keys in general that I can use? This is quite helpful, once custom input source starts working again.

**Comment by TheEngineerGuy** [comment] 2020-07-23 18:51
Hmm.. So I tried a couple of different ways for defining the inputs:

```
                        {
                            "name": "AndroidTV",
                            "keys": "hdmi3"
                        },
                        {
                            "name": "AndroidTVAN",
                            "keys": "anynet"
                        }
```

And

```
                        {
                            "name": "AndroidTV",
                            "keys": "KEY_HDMI3"
                        },
                        {
                            "name": "AndroidTVAN",
                            "keys": "KEY_ANYNET"
                        }
```

So the inputs show up, but the when I trigger them, nothing happens. While power off and switch input to 'Live TV' works just fine.

Any thoughts?

**Comment by mmende** [comment] 2020-07-24 05:29
I guess these are the limitations we have to live with. Some keys just won't work with some TV's. Samsungs implementation is awfully inconsequent unfortunately.

**Comment by TheEngineerGuy** [comment] 2020-07-24 05:36
Which format should I use to try them out? "KEY_HDMI" or "hdmi"? Will either work?

**Comment by mmende** [comment] 2020-07-24 05:38
Doesn't matter. `hdmi` is mapped to KEY_HDMI for convenience.

**Comment by mmende** [comment] 2020-07-31 05:34
I am closing this issue for now since the limitations come from Samsungs implementation of the whole remote control stuff. If you have anything we could add to the docs that would have helped you here please let me know.

**Closed by mmende** 2020-07-31 05:34 UTC
